### PR TITLE
Update setup.sh

### PR DESCRIPTION
**Pull request by 4n70w4**
It's a very bad idea to do this. Very bad. Very bad. Think of another way to do it.

### CODE REVIEW

**Comment by 4n70w4** [comment]
Hi! Any news?

**Comment by justinclift** [comment]
@4n70w4 What's a better way to achieve this? :smile:

**Comment by justinclift** [comment]
@4n70w4 I can understand not wanting to add those lines to the default ~/.profile, but I'm unclear why setting the environment variables is also a bad idea.

Thoughts? :smile:

**Comment by justinclift** [comment]
@4n70w4 We've implemented a different way of doing this now, whereby we bundle a trivial shell script that adds those variables the profile and tell people to run it if they need to:

https://github.com/getredash/setup/blob/b9ee472e57b0bb78e81f0bb187e5d46e4cb02a47/setup.sh#L150-L154

That should be a better way to get it done, without breaking things for people that already use Docker Compose for other stuff.

Sound workable to you? :smile:

**Pull request closed without merging**
