### PR TITLE
docker-compose.yml: Update to v9.0.0-beta

### PR DESCRIPTION
**Pull request by jpmckinney**
As described here: https://github.com/getredash/redash/blob/master/CHANGELOG.md#upgrading

### CODE REVIEW

**Comment by justinclift** [comment]
Thanks for this @jpmckinney, I've applied this in the alternative fork [over here](https://github.com/getnewdash/setup), in case that helps. :smile:

**Comment by peter279k** [comment]
I think this PR is outdated because it releases the `v10+` version now.

**Comment by snickerjp** [comment]
The current setup.sh does not seem to produce the intended result because it replaces the version string.
I thought a different approach was needed.

ref: https://github.com/getredash/setup/blob/e611a6af966124eb974d1d953f64a10c5e9767e6/setup.sh#L69

example:
```shell
$ TZ=UTC date
Wed Aug 23 04:17:07 AM UTC 2023
$ curl -s "https://version.redash.io/api/releases?channel=stable" | json_pp | grep "docker_image" | head -n 1 | awk 'BEGIN{FS=":"}{print $3}' | awk 'BEGIN{FS="\""}{print $1}'
8.0.0.b32245
```


An idea,
To avoid misunderstandings.
Maybe make this part a placeholder with something that doesn't exist (other than version)?

ref: https://github.com/getredash/setup/blob/e611a6af966124eb974d1d953f64a10c5e9767e6/data/docker-compose.yml#L3

The other, as is also done here
Do we get rid of the Version string replacement?

ref: https://github.com/getnewdash/setup/blob/f46decba85e20408e43c311348ce2ce715297379/setup.sh#L58

**Comment by justinclift** [comment]
Hmmmm, the goal is to install the most recent "production" quality release.  There are several ways we could achieve that.

Personally, I don't have a strong preference for a "best" solution.  So, maybe pick whichever way you're most happy with and we can just use that?

If some much better idea appears later on, we can just change to that then. :smile:

**Comment by justinclift** [comment]
@jpmckinney Thanks for putting together this PR. :smile:

Looking over it, the commit that only changes the docker image version isn't needed any more (as mentioned by @peter279k).

The other commit though (removes `celery` queue, adds worker container) is still good though.

So that commit has been merged now (https://github.com/getredash/setup/commit/92ca3da2dd2e710c40f308db0f0f78a0145f3eaf).

**Pull request closed without merging**
