### PR TITLE
update setup.sh (tested with Ubuntu 20.04)

### PR DESCRIPTION
**Pull request by snickerjp**
Update `setup.sh` Tested with Ubuntu 20.04.

* Ubuntu 18.04. [Reaching end of standard support on 31 May 2023](https://ubuntu.com/18-04) issue: #43
* Tested with Ubuntu 20.04.
* Change install Docker engine from [Install Docker Engine on Ubuntu \| Docker Documentation](https://docs.docker.com/engine/install/ubuntu/) 
  * 458751b25b484095dec20501820d7553a9386a28
* Change install for `docker-compose`
  * 458751b25b484095dec20501820d7553a9386a28
  * L20,L23
* bug fix 
  * f59265d8175681e3cf9acd1b8a73d236cb78084f
```
setup.sh: 30: [[: not found
setup.sh: 35: [[: not found
setup.sh: 41: [[: not found
```
* update README
  * 4c5f62b257db07c95d34d738fcf46e76d692408c
* change chown command from #41
  * 794030ecca101117fd620a00b31703c78979fdb2
* replace /opt/redash to $REDASH_BASE_PATH from #35 
  * 98b8c51f3505921a4a4b6494913c679145c7e3c1

### CODE REVIEW

**Comment by snickerjp** [comment]
test log
```
ubuntu@ubuntu2004-redash:~/setup$ sh setup.sh 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
pwgen is already the newest version (2.08-2).
ca-certificates is already the newest version (20230311ubuntu0.20.04.1).
curl is already the newest version (7.68.0-1ubuntu2.19).
gnupg is already the newest version (2.2.19-3ubuntu2.2).
software-properties-common is already the newest version (0.99.9.11).
apt-transport-https is already the newest version (2.0.9).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
File '/etc/apt/keyrings/docker.gpg' exists. Overwrite? (y/N) y
Hit:1 https://download.docker.com/linux/ubuntu focal InRelease
Hit:2 http://security.ubuntu.com/ubuntu focal-security InRelease                                                           
Hit:3 http://iad-ad-1.clouds.archive.ubuntu.com/ubuntu focal InRelease                                                     
Hit:4 http://iad-ad-1.clouds.archive.ubuntu.com/ubuntu focal-updates InRelease
Hit:5 http://iad-ad-1.clouds.archive.ubuntu.com/ubuntu focal-backports InRelease
Reading package lists... Done
Reading package lists... Done
Building dependency tree       
Reading state information... Done
containerd.io is already the newest version (1.6.22-1).
docker-buildx-plugin is already the newest version (0.11.2-1~ubuntu.20.04~focal).
docker-ce-cli is already the newest version (5:24.0.5-1~ubuntu.20.04~focal).
docker-ce is already the newest version (5:24.0.5-1~ubuntu.20.04~focal).
docker-compose-plugin is already the newest version (2.20.2-1~ubuntu.20.04~focal).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
'/usr/local/bin/docker-compose' -> '/usr/libexec/docker/cli-plugins/docker-compose'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1076  100  1076    0     0  11955      0 --:--:-- --:--:-- --:--:-- 11955
[+] Creating 3/3
 ✔ Network redash_default       Created                                                                                                              0.1s 
 ✔ Container redash-redis-1     Created                                                                                                              0.9s 
 ✔ Container redash-postgres-1  Created                                                                                                              0.9s 
[+] Running 2/2
 ✔ Container redash-postgres-1  Started                                                                                                              0.5s 
 ✔ Container redash-redis-1     Started                                                                                                              0.4s 
[2023-08-20 15:49:35,253][PID:1][INFO][alembic.runtime.migration] Context impl PostgresqlImpl.
[2023-08-20 15:49:35,254][PID:1][INFO][alembic.runtime.migration] Will assume transactional DDL.
[2023-08-20 15:49:35,291][PID:1][INFO][alembic.runtime.migration] Running stamp_revision  -> e5c7a4e2df4d
[+] Running 7/7
 ✔ Container redash-redis-1             Running                                                                                                      0.0s 
 ✔ Container redash-postgres-1          Running                                                                                                      0.0s 
 ✔ Container redash-scheduler-1         Started                                                                                                      1.5s 
 ✔ Container redash-scheduled_worker-1  Started                                                                                                      1.4s 
 ✔ Container redash-adhoc_worker-1      Started                                                                                                      1.3s 
 ✔ Container redash-server-1            Started                                                                                                      0.8s 
 ✔ Container redash-nginx-1             Started                                                                                                      1.5s 
```

**Comment by justinclift** [comment]
Awesome, this is a really good idea! :smile:

I don't think we can do it in this PR like it is at the moment, even though it all technically works. :frowning:

That's because if we merge this PR, then the authors of those other PRs (#35, #41) will be lost from our source code history vs if we merge those first.

Instead, lets do this:

1. Merge #35 and #41 first into the `master` branch
  * They may need some clean up too?  Not sure personally. :smile:
2. Then we rebase this PR from the new `master` branch
3. Then we merge this PR

That way, the authors of those PRs are added to the commit first history + it all gets done and works.

How does that sound? :smile:

**Comment by justinclift** [comment]
I've just merged #35 and #41 into the master branch.  I'll merge in #23 soon too (next hour?), which should neaten things up.

After that, we can update this PR to match, and then merge it. :smile:

**Comment by justinclift** [comment]
I've just merged #23 now as well.

If you're ok to rebase this on `master` (will likely need some of the commits removed too), then we should be ok to merge this in the next few days. :smile:

**Comment by justinclift** [comment]
I've disabled the "Restyled" plug-in for this repo too, as it's just wasting time for people.

**Comment by snickerjp** [comment]
> Then we rebase this PR from the new master branch
> Then we merge this PR

I understand.
I will try these.

**Comment by snickerjp** [comment]
> Then we rebase this PR from the new master branch

Merged from a new master branch.
Is this correct?
Or should I rebase and force push?

**Comment by justinclift** [comment]
> Is this correct?

~It looks ok to me.  It's not causing any merge conflicts, and the changes seem ok when I look over them.~ :smile:

---

Oops.  I didn't notice the GitHub merge conflict warning text:

```
This branch cannot be rebased due to conflicts
```

I guess you'll need to rebase this or something after all. :frowning:

**Comment by snickerjp** [comment]
Understood.
I will try to rebase.

Give me some time.

**Comment by snickerjp** [comment]
I rebased and fixed it.

**Comment by justinclift** [comment]
Awesome.  Merged. :smile:

**Comment by justinclift** [comment]
Thanks heaps for this @snickerjp, that should get things off to a good start. :smile:

**Comment by snickerjp** [comment]
By this pull request,
I believe issue #5 has been merged.

**Comment by snickerjp** [comment]
I believe this pull request has resolved issue #9.

**Comment by justinclift** [comment]
@snickerjp You have the authority to close them as makes sense to you.  You don't need to ask me first. :smile:

**Comment by snickerjp** [comment]
I understand.
Close issues and PR as needed.

**Pull request merged**
